#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.jxtb.mybatis.entity
  mapperLocations: classpath:mapper/*.xml



#开发配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&useSSL=false
    username: root
    password: jxtb
    driver-class-name: com.mysql.jdbc.Driver